version: 0.{build}
skip_tags: true
environment:
  URI: https://server.gocd.cf-app.com/go/api/pipelines/deploy-msi-ketchup/schedule
  GOCD_USERNAME:
    secure: GMMfraXG/GbV7fKTx2wJyg==
  GOCD_PASSWORD:
    secure: R28UqazSA7SVBXjihv9FoA==
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
build_script:
- git submodule update --init --recursive
- powershell "& .\scripts\setup.ps1"
- scripts\make.bat
test: off
artifacts:
- path: output/*
  name: diego-windows-msi
deploy:
- provider: S3
  access_key_id: AKIAJ3M5ORCAISPRT22Q
  secret_access_key:
    secure: lMbaCusTBxZpIbSzoILyHMBkz+sVH7EwgAqI3sAVYAM92OcIzlzq1IzcB8MmnRvZ
  region: us-east-1
  bucket: diego-windows-msi
  artifact: diego-windows-msi
  set_public: true
  on:
    branch: master
after_deploy:
- ps: scripts\trigger_wats.ps1
clone_folder: c:\dwm
branches:
  only:
  - master
  - /appveyor/
